version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
  deploy:
    docker:
      - image: circleci/ruby:2.6.2-stretch-node
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/shop-api-app.git master
workflows:
   version: 2.1
   build-deploy:
     jobs:
      #  - build
       - deploy
